POST http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTRmMzI1YjY2MDZlYmI2NWM3MTcxNSIsImVtYWlsIjoibGVzYW5waUBsZXNhbnBpLmNvbSIsImlhdCI6MTY1MzkyODc1MH0.6mLldiNSTRLDmcTORibRdoQNXcRhG28wras7yYEw6fI

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
# eyJpZCI6IjYyOTRmMzI1YjY2MDZlYmI2NWM3MTcxNSIsImVtYWlsIjoibGVzYW5waUBsZXNhbnBpLmNvbSIsImlhdCI6MTY1MzkyODc1MH0.
# 6mLldiNSTRLDmcTORibRdoQNXcRhG28wras7yYEw6fI

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
# eyJpZCI6IjYyOTRmMzI1YjY2MDZlYmI2NWM3MTcxNSIsImVtYWlsIjoibGVzYW5waUBsZXNhbnBpLmNvbSIsImlhdCI6MTY1MzkyOTEwMX0.
# u0f_HXX4ERDjldWqTOM70rWTyZ33VLvAXKKKwSx4wSE