POST http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjgzYjgzNjM3YmMzZjUyNTM5MjdjMyIsImVtYWlsIjoibHVjaG9AbHVjaG8uY29tIiwiaWF0IjoxNjYwNDM2MDY3fQ.DNO7Qkm7bLw5iq2ehXjd0iz4ZIcmxk-FyyNM35iF2Gc

{
    "fcmToken": "eiqCk8EoSjOpEToHv0FvLB:APA91bF7oVviNovW-CvsLlv04FuqGaOkarFckfh7Zm1GMvG1uCTizJQW83YFt1qtC4QMsb1BT6V3EwMfz7etfXnnMoNEfYF6Op9OrfBOFQp-wAPTkR2XpsV5u7tpHTCHEjXywT4nU0sq"
}