POST http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjZlMDZiNTNiY2I5YmE0MTlmN2FmMiIsImVtYWlsIjoibHVjaG9AbHVjaG8uY29tIiwiaWF0IjoxNjYwMzU3NzE0fQ.uDhfz1kEuYKzYfkaItKD3osWMQYJyGIN3fehv-ZnUGA

// 62f70c02a1745e2087711c15