POST http://localhost:3001/api/login 
Content-Type: application/json

{
"email": "lespinerua+test@gmail.com", 
"password": "Luis1234.",
"fcmToken": "1ch01Mo2jRAutKez5RCzkok:APA91bF-nmueL8KvVl9yriylbrHCTc-MXfoOgoGRJKBh2FM_kc1kH5INIpUrEYkuLJN-M7cYpKczJcG19lawqJBkB5TZekFE4nQ-Oj5xVKjcJOv8Etg2eJkwp4n2QUh5vFuTUR-WK3Tu"
}

