POST http://localhost:3001/api/users 
Content-Type: application/json

{
"email": "anita@anita.com", 
"name": "ana", 
"phone": "04143700742",
"password": "anita",
"fcmToken": "eiqCk8EoSjOpEToHv0FvLB:APA91bF7oVviNovW-CvsLlv04FuqGaOkarFckfh7Zm1GMvG1uCTizJQW83YFt1qtC4QMsb1BT6V3EwMfz7etfXnnMoNEfYF6Op9OrfBOFQp-wAPTkR2XpsV5u7tpHTCHEjXywT4nU0sq"
}